@startuml High-level ER-Diagram

entity creature {
  name
  gender
}

entity emotion {
  name
}

entity action {
  name
}

entity location {
  name
}

entity kind {
  name
}

creature }o-d-||kind : who
creature }o-d-||location : where
creature }o-d-|{ emotion : feels
creature }o-d-|{ action : doing
creature }o-d-o| creature : mother

@enduml