@startuml Lab 1 Entity-Relation Diagram

entity creature {
    id: int <<PK>>
    --
    name: text
    kind_id: int <<FK>>
    gender: gender
    location_id: int <<FK>>
    mother_id: int <<FK>>
}

entity emotion {
    id: int <<PK>>
    --
    name: text
    description: text
}

entity action {
    id: int <<PK>>
    --
    name: text
    description: text
}

enum gender {
    MALE
    FEMALE
}

entity location {
    id: int <<PK>>
    --
    name: text
}

entity kind {
    id: int <<PK>>
    --
    name: text
}

creature --||kind
creature --o gender
creature --||location
creature --|{ emotion
creature --|{ action
creature --o| creature

note left of creature
  Как бы там ни было, вид спускающихся 
  с дерева загадочных существ
  произвел слишком тягостное 
  впечатление на динозавриху. Загоготав
  на прощание, животное подтолкнуло 
  малыша и медленно поплелось
  прочь. 
end note

@enduml